### ISSUE TITLE
Reuse projects in various multi-project templates.

### ISSUE THREAD

**Issue by farid-am** [ligershark/side-waffle#208]
I can't find a way to reuse projects in various multi-project templates, without adding the projects multiple times in the different multi-project folders. 

I want multiple multi-project templates using different project combinations without having to add the projects to all the multi-project folders. I don't want to have to make changes on several palces for te same project also the vsix wil get very big.

**Comment by sayedihashimi** [comment]
@farid-am this is not something that TemplateBuilder supports, and I'm not even sure how to support it. This seems like a fairly advanced case and correctly solving this for the general case may be very time consuming.

What I would recommend.

I think you have two options to start with.
 - Create a build process to copy the files into the correct folders for you
 - Create a custom wizard that can pull from a single source but layout each template differently

#### Create a build process to copy the files into the correct folders for you

This is probably the simplest thing to do. You just create a script to copy the projects to the correct folders under your template project. You don't need to be worried about adding the files to the template project itself. TemplateBuilder works off the file system not the project file.
One good way to implement this would be to update the .csproj file for your template project to copy the files to the folder before build. In MSBuild you can use [incremental building and partial building](http://sedodream.com/PermaLink,guid,e68c5a1b-1078-46fd-99d1-206422378c37.aspx) of targets to remove unnecessary file copies. If you're not comfortable with MSBuild then just create a .ps1 or .cmd file.

The draw back of this approach, as you mentioned is that the size of the .vsix can get large. In some cases for images you can embed it as a resource and reference that. Not sure if you can share template content though. 

#### Create a custom wizard that can pull from a single source but layout each template differently

In this case you would write a custom wizard which is referenced in the .vstemplate file for the project template. You should create wizard that can handle all the different cases. Then in the vstemplate file you can add some parameters to the template to determine the particular configuration for the specific template.

The drawback here is that you have to create your own custom wizard. I'm not sure how difficult it would be to do this specifically since I haven't tried something like this.
