### ISSUE TITLE
Update Add Template Reference

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#238]
When a user invokes Add Template Reference the following additional steps should be taken.

 - [x] Install the TemplateBuilder NuGet pkg into the target project
 - [x] Install SW Project Template files into the target project

Even I've been tripped up by this. If we do this it will make it much easier and mush less error prone.

**Comment by RandomlyKnighted** [comment]
I like this idea. It would definitely simplify the setup process a lot.

Just out of curiosity would it be possible to also remove the target project(s) from being built or is that something that has to be done manually?

**Comment by sayedihashimi** [comment]
OK cool, do you have time to work on it?

**Comment by RandomlyKnighted** [comment]
Yeah, one of my project deadline's is tomorrow night so I can start after that. I might need that Skype session on TemplateBuilder we talked about before I get started though.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi got a couple questions for you about how the Template Reference creation.

In TemplateReferenceCreator.cs, you're using the AddItem method from the Microsoft.Build.Evaluation namespace. It's first argument says that it's an item type of the added item. You passed in "TemplateReference", but I don't see where you have declared this anywhere. How does it know what that item type refers to? 

In that same line you're setting the curProjObj.AddItem to a variable called item, but then you never do anything with the variable. Was there originally a plan to do something else after adding the item?

**Comment by sayedihashimi** [comment]
In MSBuild you can add any item type. It's up to the targets to consume them. In this case I made up TemplateReference and ls.tb.targets will process those.

About the variable, no I shouldn't have assigned it.

In this case we need to find out how to add an item template into the target project from code. I emailed a few folks you are on cc.

**Comment by sayedihashimi** [comment]
In MSBuild you can add any item type. It's up to the targets to consume them. In this case I made up TemplateReference and ls.tb.targets will process those.

About the variable, no I shouldn't have assigned it.

In this case we need to find out how to add an item template into the target project from code. I emailed a few folks you are on cc.

**Comment by RandomlyKnighted** [comment]
Thanks to the [webjobsvs project](https://github.com/ligershark/webjobsvs/blob/master/src/WebJobsVs/WebJobsVsPackage.cs) I was able to pretty easily create the function to install the TemplateBuilder package.

I haven't tested it yet since I'm not done with everything yet. So it before merging we should probably make sure it installs the package to the correct project. We'll also need to create some type of logging for the exception so the user knows if the install failed. A notification to the Visual Studio status bar would be ideal, plus I'm sure we'd probably want to log the failure in the Activity log as well.

I'm still working on adding the item template to the project. I'm still trying to figure out how to convert the VSIX to a VSPackage project. Once I get that figured out it shouldn't take long to finish the rest of this.

**Comment by sayedihashimi** [comment]
Thanks @RandomlyKnighted I really appreciate that. When you are ready send a PR and I'll review everything.

Why do we need to convert the VSIX project to a VSPackage? It shouldn't be required unless I'm missing something.

**Comment by RandomlyKnighted** [comment]
Per the original description of #161 it would be a good idea to check to see if the files already exist before adding the SW Project Template Files template.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi  where does SideWaffle store the zip files of the templates that it adds to Visual Studio? I need to get the name of the template we're wanting to add programmatically.

Also When adding the template there is a required string parameter that you have to pass the function. It's a name parameter, [which you can find here](https://msdn.microsoft.com/en-us/library/envdte.projectitems.addfromtemplate%28v=vs.120%29.aspx). From what I can tell it looks like whatever we pass into it will be what the files are named. Since this is a multi file template with specific file names will passing something to this override the names they are supposed to have? If not then can I just pass it a null value?

**Comment by RandomlyKnighted** [comment]
I'm going to go ahead and close this. If we receive any error reports then we can create new issues like we're doing with the other features.
