### ISSUE TITLE
Durandal451 doesn't work

### ISSUE THREAD

**Issue by port513** [ligershark/side-waffle#256]
When trying to create a Durandal451 project it complains about missing files.
http://www.evernote.com/l/ADeyefD4c2JDb7qFGwGLumxE0E5exTHj1TI/
http://www.evernote.com/l/ADcnKGbIsFxAVbfa1EuF0D6SnxS_vAw2CG4/
http://www.evernote.com/l/ADc_nTbVSR5PbLtVE8xaVkmQKzldz84dVXk/
http://www.evernote.com/l/ADcEJvO8sqlAk41oK5OGzofM3gAwD-5glj4/
http://www.evernote.com/l/ADfgGGV837FGQoTfsQ4r3mYRVVOd9Bgor3s/

I'm using Visual Studio 2013 Professional and a Swedish version of Windows 7 x64

**Comment by sayedihashimi** [comment]
Is Durandal 451 the version we should be using? I'm trying to see if I should fix the current template or get it replaced with one that is more up to date?

**Comment by RandomlyKnighted** [comment]
@sayedihashimi It looks like the [Durandal451 project](https://github.com/Useful-Software-Solutions-Ltd/Durandal451) hasn't been updated for a while so I guess this is still considered up to date. However, Durandal451 uses Durandal 2.01 and the current [version is 2.1.0](http://durandaljs.com/downloads.html). Since Durandal451 is still technically the latest we could fix the current template and update only the Durandal files. What do you think?

**Comment by sayedihashimi** [comment]
@RandomlyKnighted that sounds like a good idea. The sad part about this is that we are having to make uninformed decisions because we do not have any telemetry/analytics. So we don't know if this template is being used or not. Ideally if it was not being used then we would remove it. I think it will be important to add telemetry so that we can make informed decisions later on. 

That's #178 so I'll work to get that started so that we can make better decisions going forward.

**Comment by sayedihashimi** [comment]
I just tried the durandal template and I got a bunch of missing file dialogs and then the project wasn't created. Is it working for you?

**Comment by port513** [comment]
This is not working, missing files...

**Comment by port513** [comment]
Oops ;) Sorry, close button is in the wrong place ;)

**Comment by RandomlyKnighted** [comment]
I am working on getting the missing files included and getting the Durandal files updated to version 2.1.0. When I get done and have tested it on my computer I'll post a link to my build of SideWaffle to get additional feedback since Durandal isn't something I've used before.

**Comment by sayedihashimi** [comment]
Ok sounds good

**Comment by RandomlyKnighted** [comment]
I got the missing files added but ran into another problem. When you run the newly created project you get an error saying that there is a missing .mdf file in the App_Data folder. I've looked and there isn't a .mdf file in either the Side-Waffle repo or in the original repo from the person who made the template. Is there a way to generate a new .mdf file (with all the data that it should have in it)?

The other question I had was in regards to one of our previous conversations. This project is located in the [TemplatePack/ProjectTemplates](https://github.com/ligershark/side-waffle/tree/master/TemplatePack/ProjectTemplates). Is this folder where projects using the old method are stored? If so, then what are your thoughts on creating a new version of this project in the [Project Templates](https://github.com/ligershark/side-waffle/tree/master/Project%20Templates) folder. I ask because I've run into issues updating some of the dependencies since it doesn't appear to be a separate project within the solution.

**Comment by sayedihashimi** [comment]
>Is there a way to generate a new .mdf file (with all the data that it should have in it)?

Not with the data in it, unless there is a script or some form of the schema+data.

>The other question I had was in regards to one of our previous conversations. This project is located in the TemplatePack/ProjectTemplates. Is this folder where projects using the old method are stored?

Yes, I think new project templates should be created the new way and in the [Project Templates](https://github.com/ligershark/side-waffle/tree/master/Project%20Templates) folder.

**Comment by RandomlyKnighted** [comment]
@sayedihashimi I've managed to get a working .mdf file for this project. While I'm working on this do we want to migrate this over to using the new method or wait until we get some statistics first?

**Comment by sayedihashimi** [comment]
Whichever is quicker to implement

**Comment by RandomlyKnighted** [comment]
Alright, here is the [current build that I have](https://onedrive.live.com/redir?resid=633497d57c52e521%21118281). I got the template working, but didn't update Durandal to 2.1.0 because none of the Durandal packages used in this project have been updated to that version yet. Once those have been updated to the newer version I'll update this template again.
