### ISSUE TITLE
Usability issues with SideWaffle settings dialog

### ISSUE THREAD

**Issue by sayedihashimi** [ligershark/side-waffle#311]
When using the SideWaffle settings dialog on a clean box there are some usability issues. I noticed the following.

 - There is no default entries (_we used to have a couple default entries that were not enabled_)
 - When the grid is empty (_default experience_) the name/url/origin are editable but it's not editing anything.
 - When adding a new source it is not enabled by default

cc @RandomlyKnighted

**Comment by RandomlyKnighted** [comment]
1. Per #226 I was under the impression that we didn't want any default entries.
  2. You have to press the New Source button in order to for it to actually add the source, then hit Apply Changes for it to update the UI. Should the textboxes be disabled until the New Source button is pressed? 
  3. Alright, that shouldn't be a problem to fix.

**Comment by sayedihashimi** [comment]
-1 ok sounds good

**Comment by RandomlyKnighted** [comment]
@sayedihashimi do you want the textboxes disabled until the "New Source" button is clicked?

**Comment by sayedihashimi** [comment]
Sorry forgot to finish the reply

1 - OK Sounds good
2 - Yes the buttons should be disabled

**Comment by RandomlyKnighted** [comment]
Alright, I'll have a PR for you this afternoon.
