### ISSUE TITLE
Angular Typescript snippet for "Directive" is not correct

### ISSUE THREAD

**Issue by StefH** [ligershark/side-waffle#96]
The generated code is like:
interface Idirectives extends ng.IDirective {
    directiveId: string;
}

interface IdirectivesScope extends ng.IScope {
    greeting: string;
    changeGreeting: () => void;
}

class directives implements Idirectives {
    static directiveId: string = "directives";
    restrict: string = "A";

    constructor(private $window: ng.IWindowService) {
    }

    link(scope: IdirectivesScope, element, attrs) {
        scope.greeting = "Hi!";
        scope.changeGreeting = () => {
            scope.greeting = "See ya!";
        };
    }
}

But I get an error from TypeScript like:
Class directives declares interface Idirectives but does not implement it: Type 'directives' is missing property 'directiveId' from type 'Idirectives'.

Is seems when adding a static property in the class does not implement the interface.

**Comment by RobHudson72** [comment]
It looks like this has been an open issue for over a year now.  Are the AngularJS templates being maintained by anyone?

**Comment by johnpapa** [comment]
It appears that its fair game for a PR , so go for it :)

All I can say I I did not write the Typsecript ones nor do I maintain them

**Comment by sayedihashimi** [comment]
If the Angular Typescript templates/snippets are not being maintained then they should be removed.

Anyone out there interested in owning them? If not I'll remove all Angular Typescript templates/snippets in a few days.

**Comment by RobHudson72** [comment]
I am really not the right person for the job.  I have never made a directive, and just barely know the basics of services and factories, much less angular internals.  However, if nobody else will do it, I will take a crack at it, so that the community doesn't lose the templates.

**Comment by bronielsen** [comment]
Hi All

I am pretty ok experienced now with angular and typescript. I am also developing an application using the combination. Therefore I potentially could take ownership. 

But I have to ask whether there really is a need. Since these templates have been broken for a while and not that many have really complained about it, maybe we could just as well just remove them?

Would like to contribute to the community. But prefer to contribute where there is a real need :-) 

Morten

Sent from my iPhone
Morten@NovakBro.dk
+45 2964 7727

**Comment by sayedihashimi** [comment]
@bronielsen I will likely remove them.

**Comment by kentcooper** [comment]
This has been fixed as well and can be closed.
